#user: vagrant
#group: vagrant
#pid: tmp/pids/thin.pid
timeout: 30
#wait: 30
#log: log/thin.log
#max_conns: 1024
#require: []
environment: production
#max_persistent_conns: 512
servers: 3
#onebyone: true
#threaded: true
#no-epoll: true
#daemonize: true
socket: tmp/sockets/thin.sock
#chdir: /u/apps/intercity_sample_app/current/