development:
  sessions:
    default:
      database: testbench_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: testbench_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: testbench_production
      hosts:
        - localhost:27017
deployment:
  sessions:
    default:
      database: testbench_production
      hosts:
        - localhost:27017